CREATE TABLE demo (
    id VARCHAR(27) PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP WITH TIME ZONE,
    nama VARCHAR NOT NULL,
    brand VARCHAR NOT NULL,
    no_hp VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    waktu VARCHAR NOT NULL,
    tanggal TIMESTAMP WITH TIME ZONE NOT NULL
);